# Change this to true when you're working on a future post
future: false

# Meta data
title: Jordan Bowman
tagline: Practical UX skills and tools
email: desk@jrdnbwmn.com
description: >- # this means to ignore newlines until "baseurl:"
  Lessons and resources from two full-time product designers.
twitter_username: jrdnbwmn
author:
  twitter: jrdnbwmn
twitter:
  username: jrdnbwmn
  card: summary_large_image
logo: /img/jordan-bowman.png
image: /img/jordan-bowman.png
social:
  name: Jordan Bowman
  links:
    - https://twitter.com/jrdnbwmn
lang: en_US
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      image: /img/default-share.png
url: 'https://www.jrdnbwmn.com' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ''

# Posts path
permalink: /post/:title/

# Collections
collections:
  tools:
    output: true
    permalink: /stack/:title
  bookmarks:
    output: true
    permalink: /bookmarks/:title

# Build settings
markdown: kramdown
postcss:
  cache: false

# Plugins
plugins:
  - jekyll-postcss
  - jekyll-admin
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-typogrify
  - jekyll-sitemap # Keep at end

# Other
timezone: America/New_York

# Exclude from the build
exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

# Keep these files safe
keep_files:
  - .git
  - .svn
  - .gitignore
  - CNAME
